
package ar.edu.utn.frre.dacs.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MathCalculationServer", targetNamespace = "http://server.ws.dacs.frre.utn.edu.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MathCalculationServer {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://server.ws.dacs.frre.utn.edu.ar/", className = "ar.edu.utn.frre.dacs.ws.client.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://server.ws.dacs.frre.utn.edu.ar/", className = "ar.edu.utn.frre.dacs.ws.client.SumResponse")
    public int sum(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
